version: "3.9"
services:
  web:
    build: .
    command: /bin/bash -c "chmod +x /code/setup.sh && /code/setup.sh"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: